name: Generate Schema Documentation

on:
  push:
    branches: [main, docs/*]
    paths:
      - "schema/**/*.json"
      - "scripts/generate-docs.js"
  pull_request:
    branches: [main]
    paths:
      - "schema/**/*.json"
      - "scripts/generate-docs.js"
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests to validate schemas
        run: npm test

      - name: Clean previous documentation
        run: npm run docs:clean

      - name: Generate documentation
        run: npm run docs:generate

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status docs/schema-reference --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/schema-reference/
          git commit -m "📖 Auto-update schema documentation

          Generated from schemas:
          $(git diff --name-only HEAD~1 HEAD -- 'schema/**/*.json' | head -5 | sed 's/^/- /')

          [skip ci]"
          git push

      - name: Upload documentation artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: schema-documentation
          path: docs/schema-reference/
          retention-days: 30

      - name: Comment on PR with documentation preview
        if: github.event_name == 'pull_request' && steps.verify-changed-files.outputs.changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Get list of generated files
            const docsDir = 'docs/schema-reference';
            const files = fs.readdirSync(docsDir, { recursive: true })
              .filter(f => f.endsWith('.md'))
              .slice(0, 10); // Limit to first 10 files
              
            const filesList = files.map(f => `- \`${f}\``).join('\n');
            const moreFiles = files.length > 10 ? `\n\n_And ${files.length - 10} more files..._` : '';

            const body = `## 📖 Schema Documentation Generated

            The following documentation files have been generated/updated:

            ${filesList}${moreFiles}

            You can download the complete documentation from the **Artifacts** section below.

            ### 📋 Summary
            - **Total files**: ${files.length}
            - **Main index**: [\`index.md\`](docs/schema-reference/index.md)
            - **Components**: \`components/\` directory
            - **Types**: \`types/\` directory

            > Documentation will be automatically committed when this PR is merged.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
